export const Types = {
    ADD_NEW_INCOME: 'ADD_NEW_INCOME',
    EDIT_INCOME: 'EDIT_INCOME',

    ADD_NEW_EXPENSES: 'ADD_NEW_EXPENSES',
    EDIT_EXPENSES: 'EDIT_EXPENSES',

    DELETE_INC: 'DELETE_INC',
    DELETE_EXP: 'DELETE_EXP',

    USE_PLAN_KIND: 'USE_PLAN_KIND',
    ADD_CALENDAR_DATE: 'ADD_CALENDAR_DATE',

    ADD_TO_TODO: 'ADD_TO_TODO',
    ADD_TO_MAIN_FOCUS: 'ADD_TO_MAIN_FOCUS',
    ADD_TO_WISHES: 'ADD_TO_WISHES',

    EDIT_TODO_PLAN: 'EDIT_TODO_PLAN',
    EDIT_MAIN_FOCUS_PLAN: 'EDIT_MAIN_FOCUS_PLAN',

    DELETE_TODO: 'DELETE_TODO',
    DELETE_MAIN_FOCUS: 'DELETE_MAIN_FOCUS',

    ADD_TIME: 'ADD_TIME'



};