export const Types = {
    ADD_NEW_INCOME: 'ADD_NEW_INCOME',
    EDIT_INCOME: 'EDIT_INCOME',

    ADD_NEW_EXPENSES: 'ADD_NEW_EXPENSES',
    EDIT_EXPENSES: 'EDIT_EXPENSES',

    DELETE_INC: 'DELETE_INC',
    DELETE_EXP: 'DELETE_EXP',

    USE_PLAN_KIND: 'USE_PLAN_KIND',
    ADD_CALENDAR_DATE: 'ADD_CALENDAR_DATE',

    ADD_TO_TODO: 'ADD_TO_TODO',
    ADD_TO_MAIN_FOCUS: 'ADD_TO_MAIN_FOCUS',
    ADD_TO_WISHES: 'ADD_TO_WISHES',

    EDIT_TODO_PLAN: 'EDIT_TODO_PLAN',
    EDIT_MAIN_FOCUS_PLAN: 'EDIT_MAIN_FOCUS_PLAN',

    DELETE_TODO: 'DELETE_TODO',
    DELETE_MAIN_FOCUS: 'DELETE_MAIN_FOCUS',

    ADD_TIME: 'ADD_TIME',


    ADD_NOTE_TEXT: 'ADD_NOTE_TEXT',
    ADD_FONT_FAMILY: 'ADD_NOTE_FONT_FAMILY',
    ADD_FONT_SIZE: 'ADD_NOTE_FONT_SIZE',
    ADD_FONT_STYLE: 'ADD_NOTE_FONT_STYLE',
    ADD_FONT_ALIGN: 'ADD_NOTE_FONT_ALIGN',
    ADD_FONT_COLOR: 'ADD_FONT_COLOR',

    ADD_NEW_NOTE: 'ADD_NEW_NOTE',

    TOGGLE_SIGN_IN: 'TOGGLE_SIGN_IN',
    ADD_SIGN_IN_OPENED_PATH: 'ADD_SIGN_IN_OPENED_PATH',

    OPEN_NOTE: 'OPEN_NOTE',
    IS_NOTE_OPEN: 'IS_NOTE_OPEN',
    IS_EDIT_OPEN: 'IS_EDIT_OPEN',
    IS_DELETE_OPEN: 'IS_DELETE_OPEN',
    EDIT_NOTE: 'EDIT_NOTE',
    DELETE_NOTE: 'DELETE_NOTE'
};